# Generated by Django 5.1.1 on 2024-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery_man', 'Delivery_man'), ('customer', 'Customer')], default='customer', max_length=15),
        ),
    ]
